#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
#include "images/welcomescreen.h"
#include "images/winner.h"
#include "images/loser.h"
#include "images/endscreen.h"

/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
  INSTRUCTION,
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
	REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;

  // Declaring variables
  Enemy enemy[5];
  Player player;

  while (1) {
    waitForVBlank();
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state) {
      case START:
      setupInitial(&player, enemy);
      	welcomeScreen(welcomescreen);
      	if(KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
      		fillScreenDMA(WHITE);
      		state = INSTRUCTION;
      	}


        // state = ?
        break;

      case INSTRUCTION:
      	instructionScreen();
      	if(KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
      		fillScreenDMA(WHITE);
      		state = PLAY;
      		gameScreen(&player, enemy, endscreen);
      	}
      	if(KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
      		state = START;
      	}
      	break;
      case PLAY:
      enemyMovement(enemy);
      int won = movePlayer(&player, currentButtons, enemy);
      if(KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
        state = START;
        break;
      }
      if(won == 1) {
        state = WIN;
      }
      if(won == 2) {
        state = LOSE;
      }
      if(won == 3) {
        fillScreenDMA(WHITE);
        gameScreen(&player, enemy, endscreen);
      }

        // state = ?
        break;
      case WIN:
      endScreen(winner);
      	if(KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
      		state = START;
      	}
        // state = ?
        break;

        // state = ?
        break;
      case LOSE:
      endScreen(loser);
      	if(KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
      		state = START;
      	}

        // state = ?
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
